set -g mouse on
set -g history-limit 9999

set-hook -g after-copy-mode 'set -p cursor-style bar'

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection-no-clear
bind -T copy-mode DoubleClick1Pane send-keys -X select-word \; send-keys -X copy-selection-no-clear

bind -n M-h if-shell -F "#{pane_at_left}"  "previous-window" "select-pane -L"
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l if-shell -F "#{pane_at_right}" "next-window" "select-pane -R"
bind -n M-n if-shell \
    'fish -c "test #{pane_width} -gt (math #{pane_height} \* 3)"' \
    'split-window -h -c "#{pane_current_path}"' \
    'split-window -v -c "#{pane_current_path}"'

bind -n C-p switch-client -T panes
bind -T panes l split-window -h -c '#{pane_current_path}'
bind -T panes d split-window -v -c '#{pane_current_path}'
bind -T panes b break-pane
bind -T panes z resize-pane -Z
bind -T panes x kill-pane

bind -n C-t switch-client -T tabs
bind -T tabs n new-window
bind -T tabs r command-prompt -p "Rename tab:" "rename-window '%%'"
